# Generated by Django 5.0.6 on 2024-07-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/%Y/%m/%d",
                        verbose_name="프로필 사진",
                    ),
                ),
                ("product_name", models.CharField(max_length=100, verbose_name="상품명")),
                ("product_price", models.IntegerField(verbose_name="가격")),
                ("product_info", models.TextField(verbose_name="상품설명")),
            ],
        ),
    ]
